### ISSUE TITLE
[REFACTOR] 보안 관련 문제 : 패스워드 salt 사용하도록 고치기

### ISSUE THREAD

**Issue by IAOON** [ramgee-zzik-nabi/application#62]
이슈
===
패스워드가 평문으로 저장되고 있습니다. 서버측에서 패스워드를 저장할 때, 간단한 salt를 사용하여 보안성을 높여야 합니다.

**Comment by cottonpup** [comment]
평문으로 저장되던 패스워드 항목을 없애고 Supabase 빌트인 JWT 를 사용하였습니다.
